### ISSUE TITLE
button하나 만들어주세요...

### ISSUE THREAD

**Issue by WonBeomChoi** [WonBeomChoi/gary-tory#1]
# 버튼만들어야됨
엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 
이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 
이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 
이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유엄청난 이유

**Comment by Yeon-seong** [comment]
네, 확인했습니다. 버튼의 디자인은 어떻게 정할까요?

**Comment by LeeMinseo0117** [comment]
이유가 정말 엄청나네요 ㅍ..푸하항

**Comment by WonBeomChoi** [comment]
> 네, 확인했습니다. 버튼의 디자인은 어떻게 정할까요?

디자인은 자유형식으로 만들어주세요
